# Generated by Django 5.0.6 on 2024-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcard_new_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='new_column',
        ),
    ]
