# Generated by Django 5.2.4 on 2025-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_remove_flashcard_new_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
