services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    volumes:
      - ./backend:/usr/src/app/backend
      - sqlite_data:/usr/src/app/backend/backend/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      # Mount source code for hot reloading, but exclude node_modules
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules  # Anonymous volume for node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For hot reloading in Docker

volumes:
  sqlite_data: