version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/backend
      - sqlite_data:/usr/src/app/backend/backend/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - node_modules:/usr/src/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  # Adds a volume to store node dependencies
  sqlite_data:
  node_modules: